In [1]:
import pandas as pd
import numpy as np

## Zbiór danych, oznaczający oceny studentów z Algorytmów i Struktur Danych 2 z roku akademickiego 2015/2016. Każde zadanie składa się z dwóch części: część na zajęciach, za którą można dostać 4p (przeważnie), a także część domową, którą wysyła się do prowadzącego mailem z domu.

In [2]:
data = pd.read_csv("AiSD2.csv",skipinitialspace=True)

In [3]:
data

,Imię,Nazwisko,Z1(4+1),Z2(4+1),Z3(4+1),Z4(4+1),Z5(2+2),Z6(4+1),Z7(4+1),Z8(4+1),Z9(4+1),Z10(4+1),Z11(4+1),Z12(4+1),Z13(5),Z14(4+1),Z15(5)
0,Anna,Nowak,2.5+1.0,4.0+1.0,2.0+0.0,1.0+2.0,1.5+2.0,2.0+0.0,0.0+NB,1.5+1.0,3.5+0.5,2.0+0.0,0.5+1.0,ZW+ZW,4.0+0.0,4.0+1.0,NaN
1,Rafał,Kowalski,3.0+0.0,2.0+0.5,2.0+1.0,1.5+1.5,2.0+1.0,1.0+0.5,0.0+NB,3.0+1.0,3.5+1.0,0.0+NB,1.0+1.0,NS.(3.0)+NS.(1.0),4.0+0.0,4.0+1.0,NaN
2,Pavlo,Wiśniewski,2.5+0.5,US+1.0,2.5+1.0,1.5+1.5,2.0+1.5,3.5+0.0,1.0+1.0,3.0+1.0,3.5+1.0,ZW+ZW,1.0+0.5,3.5+1.0,4.0+1.0,4.0+1.0,NaN
3,Aleksy,Dąbrowski,0.5+1.0,1.0+1.0,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NaN
4,Jarosław,Lewandowski,2.0+0.0,3.0+1.0,1.0+0.0,1.5+1.5,0.5+0.0,1.25+0.0,0.0+NB,2.5+0.0,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NaN
5,Bartłomiej,Wójcik,2.0+1.0,2.0+1.0,2.5+0.5,1.5+1.5,0.5+1.0,1.75+0.5,0.0+1.0,1.5+1.0,4.0+1.0,ZW+ZW,0.5+1.0,3.0+0.0,4.0+1.0,3.5+0.0,NaN
6,Łukasz,Kamiński,4.0+1.0,2.0+1.0,3.5+1.0,1.5+0.5,1.5+0.5,US+1.0,0.5+1.0,2.0+1.0,3.5+1.0,2.0+0.0,0.5+0.5,3.0+1.0,2.0+1.0,4.0+1.0,NaN
7,Oskar,Kowalczyk,4.0+0.5,4.0+1.0,2.0+1.0,4.0+2.0,2.0+1.0,1.5+0.0,1.0+1.0,4.0+1.0,4.0+1.0,1.0+0.5,0.0+NB,3.5+1.0,4.0+1.0,3.0+0.0,NaN
8,Joanna,Zielińska,2.5+0.0,US+US,0.5+0.0,1.0+0.0,0.5+1.0,1.0+0.0,0.5+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NaN
9,Oktawia,Szymański,2.5+1.0,0.0+0.0,1.0+0.5,0.0+1.5,0.5+0.5,NB+NB,0.0+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NaN
10,Patryk,Woźniak,2.0+1.0,4.0+1.0,2.5+1.0,3.0+2.0,1.0+0.5,1.0+0.5,1.0+0.5,2.0+1.0,4.0+1.0,2.0+0.5,4.0+1.0,4.0+1.0,2.0+0.0,4.0+1.0,NaN

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 17 columns):
Imię        11 non-null object
Nazwisko    11 non-null object
Z1(4+1)     11 non-null object
Z2(4+1)     11 non-null object
Z3(4+1)     11 non-null object
Z4(4+1)     11 non-null object
Z5(2+2)     11 non-null object
Z6(4+1)     11 non-null object
Z7(4+1)     11 non-null object
Z8(4+1)     11 non-null object
Z9(4+1)     11 non-null object
Z10(4+1)    11 non-null object
Z11(4+1)    11 non-null object
Z12(4+1)    11 non-null object
Z13(5)      11 non-null object
Z14(4+1)    11 non-null object
Z15(5)      0 non-null float64
dtypes: float64(1), object(16)
memory usage: 1.5+ KB

## Stworzenie kolumny z mailem wydziałowym

In [7]:
data["email"] = data["Imię"].str[0]+data["Nazwisko"]
data["email"] = data["email"].str.lower()

In [8]:
import unicodedata

In [9]:
data["email"] = data["email"].replace("ł","l")
data["email"] = data["email"].replace("Ł","L")

In [10]:
data["email"] = data["email"].str.normalize('NFD').str.encode('ascii','ignore').str.decode('utf-8')

In [11]:
data["email"] = data["email"] + "@mini.pw.edu.pl"

In [12]:
data["email"]

0           anowak@mini.pw.edu.pl
1        rkowalski@mini.pw.edu.pl
2      pwisniewski@mini.pw.edu.pl
3       adabrowski@mini.pw.edu.pl
4     jlewandowski@mini.pw.edu.pl
5          bwojcik@mini.pw.edu.pl
6         kaminski@mini.pw.edu.pl
7       okowalczyk@mini.pw.edu.pl
8       jzielinska@mini.pw.edu.pl
9       oszymanski@mini.pw.edu.pl
10        pwozniak@mini.pw.edu.pl
Name: email, dtype: object

## Stworzenie listy mailingowej

In [107]:
data["email"].str.cat(sep=",")

'anowak@mini.pw.edu.pl,rkowalski@mini.pw.edu.pl,pwisniewski@mini.pw.edu.pl,adabrowski@mini.pw.edu.pl,jlewandowski@mini.pw.edu.pl,bwojcik@mini.pw.edu.pl,kaminski@mini.pw.edu.pl,okowalczyk@mini.pw.edu.pl,jzielinska@mini.pw.edu.pl,oszymanski@mini.pw.edu.pl,pwozniak@mini.pw.edu.pl'

## Podział kolumn z punkatmi za poszczególne zadania na część laboratoryjną i domową

In [21]:
data = data.drop("Z15(5)",axis=1)

In [22]:
import re

In [35]:
col3 = data["Z1(4+1)"]

In [36]:
col3

0     2.5+1.0
1     3.0+0.0
2     2.5+0.5
3     0.5+1.0
4     2.0+0.0
5     2.0+1.0
6     4.0+1.0
7     4.0+0.5
8     2.5+0.0
9     2.5+1.0
10    2.0+1.0
Name: Z1(4+1), dtype: object

In [37]:
res = re.match('[Z](?P<name>[\d]+)\((?P<l>[\d])[\+]*(?P<d>[\d]*)',"Z15(5)").groupdict()
res

{'d': '', 'l': '5', 'name': '15'}

In [38]:
"L" + res["name"] + "(" + res["l"] + ")"

'L15(5)'

In [39]:
len(res["d"])==0

True

In [40]:
col_s = data.iloc[:,2].str.split('+',expand=True)
col_s[0]

0     2.5
1     3.0
2     2.5
3     0.5
4     2.0
5     2.0
6     4.0
7     4.0
8     2.5
9     2.5
10    2.0
Name: 0, dtype: object

In [29]:
data.columns[2]

'Z1(4+1)'

In [142]:
data2 = data.copy()
data2

,Imię,Nazwisko,Z1(4+1),Z2(4+1),Z3(4+1),Z4(4+1),Z5(2+2),Z6(4+1),Z7(4+1),Z8(4+1),Z9(4+1),Z10(4+1),Z11(4+1),Z12(4+1),Z13(5),Z14(4+1),email
0,Anna,Nowak,2.5+1.0,4.0+1.0,2.0+0.0,1.0+2.0,1.5+2.0,2.0+0.0,0.0+NB,1.5+1.0,3.5+0.5,2.0+0.0,0.5+1.0,ZW+ZW,4.0+0.0,4.0+1.0,anowak@mini.pw.edu.pl
1,Rafał,Kowalski,3.0+0.0,2.0+0.5,2.0+1.0,1.5+1.5,2.0+1.0,1.0+0.5,0.0+NB,3.0+1.0,3.5+1.0,0.0+NB,1.0+1.0,NS.(3.0)+NS.(1.0),4.0+0.0,4.0+1.0,rkowalski@mini.pw.edu.pl
2,Pavlo,Wiśniewski,2.5+0.5,US+1.0,2.5+1.0,1.5+1.5,2.0+1.5,3.5+0.0,1.0+1.0,3.0+1.0,3.5+1.0,ZW+ZW,1.0+0.5,3.5+1.0,4.0+1.0,4.0+1.0,pwisniewski@mini.pw.edu.pl
3,Aleksy,Dąbrowski,0.5+1.0,1.0+1.0,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,NA+NA,adabrowski@mini.pw.edu.pl
4,Jarosław,Lewandowski,2.0+0.0,3.0+1.0,1.0+0.0,1.5+1.5,0.5+0.0,1.25+0.0,0.0+NB,2.5+0.0,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,jlewandowski@mini.pw.edu.pl
5,Bartłomiej,Wójcik,2.0+1.0,2.0+1.0,2.5+0.5,1.5+1.5,0.5+1.0,1.75+0.5,0.0+1.0,1.5+1.0,4.0+1.0,ZW+ZW,0.5+1.0,3.0+0.0,4.0+1.0,3.5+0.0,bwojcik@mini.pw.edu.pl
6,Łukasz,Kamiński,4.0+1.0,2.0+1.0,3.5+1.0,1.5+0.5,1.5+0.5,US+1.0,0.5+1.0,2.0+1.0,3.5+1.0,2.0+0.0,0.5+0.5,3.0+1.0,2.0+1.0,4.0+1.0,kaminski@mini.pw.edu.pl
7,Oskar,Kowalczyk,4.0+0.5,4.0+1.0,2.0+1.0,4.0+2.0,2.0+1.0,1.5+0.0,1.0+1.0,4.0+1.0,4.0+1.0,1.0+0.5,0.0+NB,3.5+1.0,4.0+1.0,3.0+0.0,okowalczyk@mini.pw.edu.pl
8,Joanna,Zielińska,2.5+0.0,US+US,0.5+0.0,1.0+0.0,0.5+1.0,1.0+0.0,0.5+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,jzielinska@mini.pw.edu.pl
9,Oktawia,Szymański,2.5+1.0,0.0+0.0,1.0+0.5,0.0+1.5,0.5+0.5,NB+NB,0.0+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,NB+NB,oszymanski@mini.pw.edu.pl
10,Patryk,Woźniak,2.0+1.0,4.0+1.0,2.5+1.0,3.0+2.0,1.0+0.5,1.0+0.5,1.0+0.5,2.0+1.0,4.0+1.0,2.0+0.5,4.0+1.0,4.0+1.0,2.0+0.0,4.0+1.0,pwozniak@mini.pw.edu.pl

In [143]:
def split_col(df,col_index):
    col_i_name = df.columns[col_index]
    #print(col_i_name)
    res = re.match('[Z](?P<name>[\d]+)\((?P<l>[\d])[\+]*(?P<d>[\d]*)',col_i_name).groupdict()
    
    L_i = "L" + res["name"] + "(" + res["l"] + ")"
    #print(L_i)

    col_splitted = df.iloc[:,col_index].str.split('+',expand=True)
    
    if len(res["d"]) != 0:
        D_i = "D" + res["name"] + "(" + res["d"] + ")"
        #print(D_i)
        df[L_i] = col_splitted[0]
        df[D_i] = col_splitted[1]
    else:
        df[L_i] = col_splitted[0]        
    return df

In [144]:
data2.shape

(11, 17)

In [145]:
indexes = []
for c in range(2,data2.shape[1]-1):
    split_col(data2,c)
    indexes.append(c)
data2.drop(data2.columns[indexes], axis=1, inplace=True)

In [146]:
data2

,Imię,Nazwisko,email,L1(4),D1(1),L2(4),D2(1),L3(4),D3(1),L4(4),...,D9(1),L10(4),D10(1),L11(4),D11(1),L12(4),D12(1),L13(5),L14(4),D14(1)
0,Anna,Nowak,anowak@mini.pw.edu.pl,2.5,1.0,4.0,1.0,2.0,0.0,1.0,...,0.5,2.0,0.0,0.5,1.0,ZW,ZW,4.0,4.0,1.0
1,Rafał,Kowalski,rkowalski@mini.pw.edu.pl,3.0,0.0,2.0,0.5,2.0,1.0,1.5,...,1.0,0.0,NB,1.0,1.0,NS.(3.0),NS.(1.0),4.0,4.0,1.0
2,Pavlo,Wiśniewski,pwisniewski@mini.pw.edu.pl,2.5,0.5,US,1.0,2.5,1.0,1.5,...,1.0,ZW,ZW,1.0,0.5,3.5,1.0,4.0,4.0,1.0
3,Aleksy,Dąbrowski,adabrowski@mini.pw.edu.pl,0.5,1.0,1.0,1.0,NA,NA,NA,...,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
4,Jarosław,Lewandowski,jlewandowski@mini.pw.edu.pl,2.0,0.0,3.0,1.0,1.0,0.0,1.5,...,NB,NB,NB,NB,NB,NB,NB,NB,NB,NB
5,Bartłomiej,Wójcik,bwojcik@mini.pw.edu.pl,2.0,1.0,2.0,1.0,2.5,0.5,1.5,...,1.0,ZW,ZW,0.5,1.0,3.0,0.0,4.0,3.5,0.0
6,Łukasz,Kamiński,kaminski@mini.pw.edu.pl,4.0,1.0,2.0,1.0,3.5,1.0,1.5,...,1.0,2.0,0.0,0.5,0.5,3.0,1.0,2.0,4.0,1.0
7,Oskar,Kowalczyk,okowalczyk@mini.pw.edu.pl,4.0,0.5,4.0,1.0,2.0,1.0,4.0,...,1.0,1.0,0.5,0.0,NB,3.5,1.0,4.0,3.0,0.0
8,Joanna,Zielińska,jzielinska@mini.pw.edu.pl,2.5,0.0,US,US,0.5,0.0,1.0,...,NB,NB,NB,NB,NB,NB,NB,NB,NB,NB
9,Oktawia,Szymański,oszymanski@mini.pw.edu.pl,2.5,1.0,0.0,0.0,1.0,0.5,0.0,...,NB,NB,NB,NB,NB,NB,NB,NB,NB,NB
10,Patryk,Woźniak,pwozniak@mini.pw.edu.pl,2.0,1.0,4.0,1.0,2.5,1.0,3.0,...,1.0,2.0,0.5,4.0,1.0,4.0,1.0,2.0,4.0,1.0

## Zamiana NA, NB, NS na 0 punktów

In [147]:
data2 = data2.replace(["NA","NB",r"NS\.\(.+\)","0"],"0",regex=True)
data2

,Imię,Nazwisko,email,L1(4),D1(1),L2(4),D2(1),L3(4),D3(1),L4(4),...,D9(1),L10(4),D10(1),L11(4),D11(1),L12(4),D12(1),L13(5),L14(4),D14(1)
0,Anna,Nowak,anowak@mini.pw.edu.pl,2.5,1.0,4.0,1.0,2.0,0.0,1.0,...,0.5,2.0,0.0,0.5,1.0,ZW,ZW,4.0,4.0,1.0
1,Rafał,Kowalski,rkowalski@mini.pw.edu.pl,3.0,0.0,2.0,0.5,2.0,1.0,1.5,...,1.0,0.0,0,1.0,1.0,0,0,4.0,4.0,1.0
2,Pavlo,Wiśniewski,pwisniewski@mini.pw.edu.pl,2.5,0.5,US,1.0,2.5,1.0,1.5,...,1.0,ZW,ZW,1.0,0.5,3.5,1.0,4.0,4.0,1.0
3,Aleksy,Dąbrowski,adabrowski@mini.pw.edu.pl,0.5,1.0,1.0,1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Jarosław,Lewandowski,jlewandowski@mini.pw.edu.pl,2.0,0.0,3.0,1.0,1.0,0.0,1.5,...,0,0,0,0,0,0,0,0,0,0
5,Bartłomiej,Wójcik,bwojcik@mini.pw.edu.pl,2.0,1.0,2.0,1.0,2.5,0.5,1.5,...,1.0,ZW,ZW,0.5,1.0,3.0,0.0,4.0,3.5,0.0
6,Łukasz,Kamiński,kaminski@mini.pw.edu.pl,4.0,1.0,2.0,1.0,3.5,1.0,1.5,...,1.0,2.0,0.0,0.5,0.5,3.0,1.0,2.0,4.0,1.0
7,Oskar,Kowalczyk,okowalczyk@mini.pw.edu.pl,4.0,0.5,4.0,1.0,2.0,1.0,4.0,...,1.0,1.0,0.5,0.0,0,3.5,1.0,4.0,3.0,0.0
8,Joanna,Zielińska,jzielinska@mini.pw.edu.pl,2.5,0.0,US,US,0.5,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
9,Oktawia,Szymański,oszymanski@mini.pw.edu.pl,2.5,1.0,0.0,0.0,1.0,0.5,0.0,...,0,0,0,0,0,0,0,0,0,0
10,Patryk,Woźniak,pwozniak@mini.pw.edu.pl,2.0,1.0,4.0,1.0,2.5,1.0,3.0,...,1.0,2.0,0.5,4.0,1.0,4.0,1.0,2.0,4.0,1.0

## Zamiana ZW i US na punkty będące średnią z dwóch wartości - średniej wartości z danej kolumny i danego wiersza

In [148]:
data2 = data2.replace(["ZW","US"],np.nan)

In [149]:
data2

,Imię,Nazwisko,email,L1(4),D1(1),L2(4),D2(1),L3(4),D3(1),L4(4),...,D9(1),L10(4),D10(1),L11(4),D11(1),L12(4),D12(1),L13(5),L14(4),D14(1)
0,Anna,Nowak,anowak@mini.pw.edu.pl,2.5,1.0,4.0,1.0,2.0,0.0,1.0,...,0.5,2.0,0.0,0.5,1.0,NaN,NaN,4.0,4.0,1.0
1,Rafał,Kowalski,rkowalski@mini.pw.edu.pl,3.0,0.0,2.0,0.5,2.0,1.0,1.5,...,1.0,0.0,0,1.0,1.0,0,0,4.0,4.0,1.0
2,Pavlo,Wiśniewski,pwisniewski@mini.pw.edu.pl,2.5,0.5,NaN,1.0,2.5,1.0,1.5,...,1.0,NaN,NaN,1.0,0.5,3.5,1.0,4.0,4.0,1.0
3,Aleksy,Dąbrowski,adabrowski@mini.pw.edu.pl,0.5,1.0,1.0,1.0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Jarosław,Lewandowski,jlewandowski@mini.pw.edu.pl,2.0,0.0,3.0,1.0,1.0,0.0,1.5,...,0,0,0,0,0,0,0,0,0,0
5,Bartłomiej,Wójcik,bwojcik@mini.pw.edu.pl,2.0,1.0,2.0,1.0,2.5,0.5,1.5,...,1.0,NaN,NaN,0.5,1.0,3.0,0.0,4.0,3.5,0.0
6,Łukasz,Kamiński,kaminski@mini.pw.edu.pl,4.0,1.0,2.0,1.0,3.5,1.0,1.5,...,1.0,2.0,0.0,0.5,0.5,3.0,1.0,2.0,4.0,1.0
7,Oskar,Kowalczyk,okowalczyk@mini.pw.edu.pl,4.0,0.5,4.0,1.0,2.0,1.0,4.0,...,1.0,1.0,0.5,0.0,0,3.5,1.0,4.0,3.0,0.0
8,Joanna,Zielińska,jzielinska@mini.pw.edu.pl,2.5,0.0,NaN,NaN,0.5,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
9,Oktawia,Szymański,oszymanski@mini.pw.edu.pl,2.5,1.0,0.0,0.0,1.0,0.5,0.0,...,0,0,0,0,0,0,0,0,0,0
10,Patryk,Woźniak,pwozniak@mini.pw.edu.pl,2.0,1.0,4.0,1.0,2.5,1.0,3.0,...,1.0,2.0,0.5,4.0,1.0,4.0,1.0,2.0,4.0,1.0

In [150]:
data2.shape

(11, 30)

In [151]:
float_data = data2.iloc[:,3:data2.shape[1]].astype(float)

In [152]:
data2 = pd.concat([data2.iloc[:,0:3],float_data],axis=1)

In [153]:
data2

,Imię,Nazwisko,email,L1(4),D1(1),L2(4),D2(1),L3(4),D3(1),L4(4),...,D9(1),L10(4),D10(1),L11(4),D11(1),L12(4),D12(1),L13(5),L14(4),D14(1)
0,Anna,Nowak,anowak@mini.pw.edu.pl,2.5,1.0,4.0,1.0,2.0,0.0,1.0,...,0.5,2.0,0.0,0.5,1.0,NaN,NaN,4.0,4.0,1.0
1,Rafał,Kowalski,rkowalski@mini.pw.edu.pl,3.0,0.0,2.0,0.5,2.0,1.0,1.5,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,4.0,1.0
2,Pavlo,Wiśniewski,pwisniewski@mini.pw.edu.pl,2.5,0.5,NaN,1.0,2.5,1.0,1.5,...,1.0,NaN,NaN,1.0,0.5,3.5,1.0,4.0,4.0,1.0
3,Aleksy,Dąbrowski,adabrowski@mini.pw.edu.pl,0.5,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Jarosław,Lewandowski,jlewandowski@mini.pw.edu.pl,2.0,0.0,3.0,1.0,1.0,0.0,1.5,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Bartłomiej,Wójcik,bwojcik@mini.pw.edu.pl,2.0,1.0,2.0,1.0,2.5,0.5,1.5,...,1.0,NaN,NaN,0.5,1.0,3.0,0.0,4.0,3.5,0.0
6,Łukasz,Kamiński,kaminski@mini.pw.edu.pl,4.0,1.0,2.0,1.0,3.5,1.0,1.5,...,1.0,2.0,0.0,0.5,0.5,3.0,1.0,2.0,4.0,1.0
7,Oskar,Kowalczyk,okowalczyk@mini.pw.edu.pl,4.0,0.5,4.0,1.0,2.0,1.0,4.0,...,1.0,1.0,0.5,0.0,0.0,3.5,1.0,4.0,3.0,0.0
8,Joanna,Zielińska,jzielinska@mini.pw.edu.pl,2.5,0.0,NaN,NaN,0.5,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,Oktawia,Szymański,oszymanski@mini.pw.edu.pl,2.5,1.0,0.0,0.0,1.0,0.5,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,Patryk,Woźniak,pwozniak@mini.pw.edu.pl,2.0,1.0,4.0,1.0,2.5,1.0,3.0,...,1.0,2.0,0.5,4.0,1.0,4.0,1.0,2.0,4.0,1.0

In [154]:
for c in range(3,data2.shape[1]):
    indexes = data2[data2.iloc[:,c].isnull()].index
    if indexes.size > 0:
        mean1 = data2.iloc[:,c].mean()
        for ind in indexes:
            data2.iloc[ind,c] = (mean1 + data2.iloc[ind,3:data2.shape[1]].mean())/2

In [155]:
data2

,Imię,Nazwisko,email,L1(4),D1(1),L2(4),D2(1),L3(4),D3(1),L4(4),...,D9(1),L10(4),D10(1),L11(4),D11(1),L12(4),D12(1),L13(5),L14(4),D14(1)
0,Anna,Nowak,anowak@mini.pw.edu.pl,2.5,1.0,4.000000,1.000000,2.0,0.0,1.0,...,0.5,2.000000,0.000000,0.5,1.0,1.61,0.961731,4.0,4.0,1.0
1,Rafał,Kowalski,rkowalski@mini.pw.edu.pl,3.0,0.0,2.000000,0.500000,2.0,1.0,1.5,...,1.0,0.000000,0.000000,1.0,1.0,0.00,0.000000,4.0,4.0,1.0
2,Pavlo,Wiśniewski,pwisniewski@mini.pw.edu.pl,2.5,0.5,2.118056,1.000000,2.5,1.0,1.5,...,1.0,1.291250,0.948042,1.0,0.5,3.50,1.000000,4.0,4.0,1.0
3,Aleksy,Dąbrowski,adabrowski@mini.pw.edu.pl,0.5,1.0,1.000000,1.000000,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0.0
4,Jarosław,Lewandowski,jlewandowski@mini.pw.edu.pl,2.0,0.0,3.000000,1.000000,1.0,0.0,1.5,...,0.0,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0.0
5,Bartłomiej,Wójcik,bwojcik@mini.pw.edu.pl,2.0,1.0,2.000000,1.000000,2.5,0.5,1.5,...,1.0,1.113889,0.774092,0.5,1.0,3.00,0.000000,4.0,3.5,0.0
6,Łukasz,Kamiński,kaminski@mini.pw.edu.pl,4.0,1.0,2.000000,1.000000,3.5,1.0,1.5,...,1.0,2.000000,0.000000,0.5,0.5,3.00,1.000000,2.0,4.0,1.0
7,Oskar,Kowalczyk,okowalczyk@mini.pw.edu.pl,4.0,0.5,4.000000,1.000000,2.0,1.0,4.0,...,1.0,1.000000,0.500000,0.0,0.0,3.50,1.000000,4.0,3.0,0.0
8,Joanna,Zielińska,jzielinska@mini.pw.edu.pl,2.5,0.0,1.362222,0.585812,0.5,0.0,1.0,...,0.0,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0.0
9,Oktawia,Szymański,oszymanski@mini.pw.edu.pl,2.5,1.0,0.000000,0.000000,1.0,0.5,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0.0
10,Patryk,Woźniak,pwozniak@mini.pw.edu.pl,2.0,1.0,4.000000,1.000000,2.5,1.0,3.0,...,1.0,2.000000,0.500000,4.0,1.0,4.00,1.000000,2.0,4.0,1.0

## Oceny końcowe wg schematu: 
** [0%,50%) -> 2 
[51%,60%) -> 3 
[61%,70%) -> 3.5 
[71%,80%) -> 4 
 [81%,90%) -> 4.5 
 [91%,Inf] -> 5**

In [156]:
sum_max = 0 #maksymalna suma punktów możliwa do uzyskania
for col in data2.iloc[:,3:data2.shape[1]].columns:
    sum_max += float(re.findall("\(([\d])\)",col)[0])
sum_max

69.0

In [157]:
data2["suma"] = data2.sum(axis=1)

In [158]:
data2["procenty"] = data2["suma"]/sum_max * 100

In [159]:
data2

,Imię,Nazwisko,email,L1(4),D1(1),L2(4),D2(1),L3(4),D3(1),L4(4),...,D10(1),L11(4),D11(1),L12(4),D12(1),L13(5),L14(4),D14(1),suma,procenty
0,Anna,Nowak,anowak@mini.pw.edu.pl,2.5,1.0,4.000000,1.000000,2.0,0.0,1.0,...,0.000000,0.5,1.0,1.61,0.961731,4.0,4.0,1.0,40.571731,58.799610
1,Rafał,Kowalski,rkowalski@mini.pw.edu.pl,3.0,0.0,2.000000,0.500000,2.0,1.0,1.5,...,0.000000,1.0,1.0,0.00,0.000000,4.0,4.0,1.0,35.500000,51.449275
2,Pavlo,Wiśniewski,pwisniewski@mini.pw.edu.pl,2.5,0.5,2.118056,1.000000,2.5,1.0,1.5,...,0.948042,1.0,0.5,3.50,1.000000,4.0,4.0,1.0,47.357348,68.633837
3,Aleksy,Dąbrowski,adabrowski@mini.pw.edu.pl,0.5,1.0,1.000000,1.000000,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,3.500000,5.072464
4,Jarosław,Lewandowski,jlewandowski@mini.pw.edu.pl,2.0,0.0,3.000000,1.000000,1.0,0.0,1.5,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,14.250000,20.652174
5,Bartłomiej,Wójcik,bwojcik@mini.pw.edu.pl,2.0,1.0,2.000000,1.000000,2.5,0.5,1.5,...,0.774092,0.5,1.0,3.00,0.000000,4.0,3.5,0.0,38.137981,55.272436
6,Łukasz,Kamiński,kaminski@mini.pw.edu.pl,4.0,1.0,2.000000,1.000000,3.5,1.0,1.5,...,0.000000,0.5,0.5,3.00,1.000000,2.0,4.0,1.0,41.928846,60.766444
7,Oskar,Kowalczyk,okowalczyk@mini.pw.edu.pl,4.0,0.5,4.000000,1.000000,2.0,1.0,4.0,...,0.500000,0.0,0.0,3.50,1.000000,4.0,3.0,0.0,48.000000,69.565217
8,Joanna,Zielińska,jzielinska@mini.pw.edu.pl,2.5,0.0,1.362222,0.585812,0.5,0.0,1.0,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,8.948034,12.968165
9,Oktawia,Szymański,oszymanski@mini.pw.edu.pl,2.5,1.0,0.000000,0.000000,1.0,0.5,0.0,...,0.000000,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,7.500000,10.869565
10,Patryk,Woźniak,pwozniak@mini.pw.edu.pl,2.0,1.0,4.000000,1.000000,2.5,1.0,3.0,...,0.500000,4.0,1.0,4.00,1.000000,2.0,4.0,1.0,48.500000,70.289855

In [160]:
data2["ocena"] = pd.cut(data2["procenty"],[0,50,60,70,80,90,100],labels=[2.0,3.0,3.5,4.0,4.5,5.0])

In [161]:
data2

,Imię,Nazwisko,email,L1(4),D1(1),L2(4),D2(1),L3(4),D3(1),L4(4),...,L11(4),D11(1),L12(4),D12(1),L13(5),L14(4),D14(1),suma,procenty,ocena
0,Anna,Nowak,anowak@mini.pw.edu.pl,2.5,1.0,4.000000,1.000000,2.0,0.0,1.0,...,0.5,1.0,1.61,0.961731,4.0,4.0,1.0,40.571731,58.799610,3.0
1,Rafał,Kowalski,rkowalski@mini.pw.edu.pl,3.0,0.0,2.000000,0.500000,2.0,1.0,1.5,...,1.0,1.0,0.00,0.000000,4.0,4.0,1.0,35.500000,51.449275,3.0
2,Pavlo,Wiśniewski,pwisniewski@mini.pw.edu.pl,2.5,0.5,2.118056,1.000000,2.5,1.0,1.5,...,1.0,0.5,3.50,1.000000,4.0,4.0,1.0,47.357348,68.633837,3.5
3,Aleksy,Dąbrowski,adabrowski@mini.pw.edu.pl,0.5,1.0,1.000000,1.000000,0.0,0.0,0.0,...,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,3.500000,5.072464,2.0
4,Jarosław,Lewandowski,jlewandowski@mini.pw.edu.pl,2.0,0.0,3.000000,1.000000,1.0,0.0,1.5,...,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,14.250000,20.652174,2.0
5,Bartłomiej,Wójcik,bwojcik@mini.pw.edu.pl,2.0,1.0,2.000000,1.000000,2.5,0.5,1.5,...,0.5,1.0,3.00,0.000000,4.0,3.5,0.0,38.137981,55.272436,3.0
6,Łukasz,Kamiński,kaminski@mini.pw.edu.pl,4.0,1.0,2.000000,1.000000,3.5,1.0,1.5,...,0.5,0.5,3.00,1.000000,2.0,4.0,1.0,41.928846,60.766444,3.5
7,Oskar,Kowalczyk,okowalczyk@mini.pw.edu.pl,4.0,0.5,4.000000,1.000000,2.0,1.0,4.0,...,0.0,0.0,3.50,1.000000,4.0,3.0,0.0,48.000000,69.565217,3.5
8,Joanna,Zielińska,jzielinska@mini.pw.edu.pl,2.5,0.0,1.362222,0.585812,0.5,0.0,1.0,...,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,8.948034,12.968165,2.0
9,Oktawia,Szymański,oszymanski@mini.pw.edu.pl,2.5,1.0,0.000000,0.000000,1.0,0.5,0.0,...,0.0,0.0,0.00,0.000000,0.0,0.0,0.0,7.500000,10.869565,2.0
10,Patryk,Woźniak,pwozniak@mini.pw.edu.pl,2.0,1.0,4.000000,1.000000,2.5,1.0,3.0,...,4.0,1.0,4.00,1.000000,2.0,4.0,1.0,48.500000,70.289855,4.0